package android.tvz.hr.clienttracker.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00687B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)


val md_theme_light_primaryContainer = Color(0xFFAFECFF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F27)
val md_theme_light_secondary = Color(0xFF4B6269)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCEE7EF)
val md_theme_light_onSecondaryContainer = Color(0xFF061F25)
val md_theme_light_tertiary = Color(0xFF575C7E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDEE0FF)
val md_theme_light_onTertiaryContainer = Color(0xFF141937)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFCFE)
val md_theme_light_onBackground = Color(0xFF191C1D)
val md_theme_light_surface = Color(0xFFFBFCFE)
val md_theme_light_onSurface = Color(0xFF191C1D)
val md_theme_light_surfaceVariant = Color(0xFFDBE4E7)
val md_theme_light_onSurfaceVariant = Color(0xFF40484B)
val md_theme_light_outline = Color(0xFF70787C)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F2)
val md_theme_light_inverseSurface = Color(0xFF2E3132)
val md_theme_light_inversePrimary = Color(0xFF57D6F6)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00687B)
val md_theme_light_outlineVariant = Color(0xFFBFC8CB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF57D6F6)
val md_theme_dark_onPrimary = Color(0xFF003641)
val md_theme_dark_primaryContainer = Color(0xFF004E5D)
val md_theme_dark_onPrimaryContainer = Color(0xFFAFECFF)
val md_theme_dark_secondary = Color(0xFFB2CBD3)
val md_theme_dark_onSecondary = Color(0xFF1D343A)
val md_theme_dark_secondaryContainer = Color(0xFF344A51)
val md_theme_dark_onSecondaryContainer = Color(0xFFCEE7EF)
val md_theme_dark_tertiary = Color(0xFFC0C4EB)
val md_theme_dark_onTertiary = Color(0xFF292E4D)
val md_theme_dark_tertiaryContainer = Color(0xFF404565)
val md_theme_dark_onTertiaryContainer = Color(0xFFDEE0FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1D)
val md_theme_dark_onBackground = Color(0xFFE1E3E4)
val md_theme_dark_surface = Color(0xFF191C1D)
val md_theme_dark_onSurface = Color(0xFFE1E3E4)
val md_theme_dark_surfaceVariant = Color(0xFF40484B)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CB)
val md_theme_dark_outline = Color(0xFF899295)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E4)
val md_theme_dark_inversePrimary = Color(0xFF00687B)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF57D6F6)
val md_theme_dark_outlineVariant = Color(0xFF40484B)
val md_theme_dark_scrim = Color(0xFF000000)

val lightGreen = Color(0xFFd7f5ec)
val lightRed = Color(0xFFf8e2e0)
val lightPurple = Color(0xFFdfe3f6)
val lightBlue = Color(0xFFdaf1f9)


val seed = Color(0xFFDAF1F9)
val light_green = Color(0xFFD7F5EC)
val orange = Color(0xFFE37A56)
val backgorund_color = Color(0xFFF7F8F8)
val light_red = Color(0xFFF8E2E0)
val light_purple = Color(0xFFDFE3F6)
val light_light_green = Color(0xFF006B5C)
val light_onlight_green = Color(0xFFFFFFFF)
val light_light_greenContainer = Color(0xFF78F8DE)
val light_onlight_greenContainer = Color(0xFF00201B)
val dark_light_green = Color(0xFF58DBC2)
val dark_onlight_green = Color(0xFF00382F)
val dark_light_greenContainer = Color(0xFF005045)
val dark_onlight_greenContainer = Color(0xFF78F8DE)
val light_orange = Color(0xFF9C4424)
val light_onorange = Color(0xFFFFFFFF)
val light_orangeContainer = Color(0xFFFFDBD0)
val light_onorangeContainer = Color(0xFF390C00)
val dark_orange = Color(0xFFFFB59D)
val dark_onorange = Color(0xFF5D1900)
val dark_orangeContainer = Color(0xFF7D2D0F)
val dark_onorangeContainer = Color(0xFFFFDBD0)
val light_backgorund_color = Color(0xFF006972)
val light_onbackgorund_color = Color(0xFFFFFFFF)
val light_backgorund_colorContainer = Color(0xFF8DF2FF)
val light_onbackgorund_colorContainer = Color(0xFF001F23)
val dark_backgorund_color = Color(0xFF4ED8E8)
val dark_onbackgorund_color = Color(0xFF00363C)
val dark_backgorund_colorContainer = Color(0xFF004F56)
val dark_onbackgorund_colorContainer = Color(0xFF8DF2FF)
val light_light_red = Color(0xFF9C413E)
val light_onlight_red = Color(0xFFFFFFFF)
val light_light_redContainer = Color(0xFFFFDAD7)
val light_onlight_redContainer = Color(0xFF410004)
val dark_light_red = Color(0xFFFFB3AE)
val dark_onlight_red = Color(0xFF5F1415)
val dark_light_redContainer = Color(0xFF7E2A29)
val dark_onlight_redContainer = Color(0xFFFFDAD7)
val light_light_purple = Color(0xFF385BA9)
val light_onlight_purple = Color(0xFFFFFFFF)
val light_light_purpleContainer = Color(0xFFDAE2FF)
val light_onlight_purpleContainer = Color(0xFF001946)
val dark_light_purple = Color(0xFFB1C5FF)
val dark_onlight_purple = Color(0xFF002C70)
val dark_light_purpleContainer = Color(0xFF1B438F)
val dark_onlight_purpleContainer = Color(0xFFDAE2FF)

val graph_color = Color(0xFFc1dff7)



